version: "3.8"
services:
  web:
    build: web
    restart: always
    container_name: aperisolve_web
    volumes:
    - ./web:/app
    ports:
      - "5000:5000"
  backend:
    build: backend
    restart: always
    container_name: aperisolve_back
    volumes:
    - ./backend:/app
    - ./web/static/uploads:/app/uploads
